-- MySQL Script generated by MySQL Workbench
-- Tue Jul  7 16:07:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema langalike_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema langalike_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `langalike_db` DEFAULT CHARACTER SET utf8 ;
USE `langalike_db` ;

-- -----------------------------------------------------
-- Table `langalike_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `langalike_db`.`user` ;

CREATE TABLE IF NOT EXISTS `langalike_db`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `secret` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `langalike_db`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `langalike_db`.`score` ;

CREATE TABLE IF NOT EXISTS `langalike_db`.`score` (
  `id` INT NOT NULL,
  `value` INT NULL,
  `time` INT NULL,
  `user_id` INT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_score_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_score_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `langalike_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `langalike_db`.`review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `langalike_db`.`review` ;

CREATE TABLE IF NOT EXISTS `langalike_db`.`review` (
  `id` INT NOT NULL,
  `content` VARCHAR(255) NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_review_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_review_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `langalike_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
